// utils/generateReport.js

import jsPDF from "jspdf";

import autoTable from "jspdf-autotable";

import formatCurrency from "./formatCurrency";

import formatDate from "./formatDate";

/* ======================================================
   GENERATE PDF REPORT
====================================================== */

const generateReport = ({
    title = "Admin Report",

    fileName = "report.pdf",

    columns = [],

    data = [],

    summary = {},

    generatedBy = "Admin",
}) => {
    try {
        /* ======================================================
           PDF DOCUMENT
        ====================================================== */

        const doc = new jsPDF();

        /* ======================================================
           HEADER
        ====================================================== */

        doc.setFontSize(22);

        doc.setTextColor(255, 102, 0);

        doc.text(title, 14, 20);

        /* ======================================================
           SUB HEADER
        ====================================================== */

        doc.setFontSize(11);

        doc.setTextColor(100);

        doc.text(
            `Generated By: ${generatedBy}`,
            14,
            30
        );

        doc.text(
            `Generated On: ${formatDate(
                new Date(),
                "en-IN",
                {
                    day: "2-digit",
                    month: "long",
                    year: "numeric",
                }
            )}`,
            14,
            37
        );

        /* ======================================================
           SUMMARY SECTION
        ====================================================== */

        let currentY = 50;

        if (Object.keys(summary).length > 0) {
            doc.setFontSize(14);

            doc.setTextColor(40);

            doc.text("Report Summary", 14, currentY);

            currentY += 10;

            Object.entries(summary).forEach(
                ([key, value]) => {
                    const formattedKey = key
                        .replace(/([A-Z])/g, " $1")
                        .replace(/^./, (str) =>
                            str.toUpperCase()
                        );

                    let formattedValue = value;

                    if (
                        typeof value === "number" &&
                        key.toLowerCase().includes("amount")
                    ) {
                        formattedValue =
                            formatCurrency(value);
                    }

                    doc.setFontSize(11);

                    doc.setTextColor(80);

                    doc.text(
                        `${formattedKey}: ${formattedValue}`,
                        16,
                        currentY
                    );

                    currentY += 7;
                }
            );

            currentY += 10;
        }

        /* ======================================================
           TABLE
        ====================================================== */

        autoTable(doc, {
            startY: currentY,

            head: [columns],

            body: data,

            theme: "striped",

            headStyles: {
                fillColor: [255, 102, 0],

                textColor: [255, 255, 255],

                fontStyle: "bold",
            },

            styles: {
                fontSize: 10,

                cellPadding: 4,
            },

            alternateRowStyles: {
                fillColor: [248, 248, 248],
            },

            margin: {
                top: 20,
            },
        });

        /* ======================================================
           FOOTER
        ====================================================== */

        const pageCount =
            doc.internal.getNumberOfPages();

        for (
            let i = 1;
            i <= pageCount;
            i++
        ) {
            doc.setPage(i);

            doc.setFontSize(10);

            doc.setTextColor(150);

            doc.text(
                `Page ${i} of ${pageCount}`,
                170,
                290
            );
        }

        /* ======================================================
           SAVE PDF
        ====================================================== */

        doc.save(fileName);

        return {
            success: true,

            message:
                "Report generated successfully",
        };
    } catch (error) {
        console.error(
            "Report generation failed:",
            error
        );

        return {
            success: false,

            message: "Failed to generate report",
        };
    }
};

export default generateReport;